### ISSUE TITLE
Submitting Comment with file not working as expected

### ISSUE THREAD

**Issue by lasdou** [scribblelive/comment-sample#1]
Hi,

i am trying to implement the scribblelive event comments form, but i am not able to validate file upload.

Once the form is submitted with an image i obtain a json response like that  : 

`{
    "Id":392789596,
    "Content":"sdfsdfdfdsf",
    "Creator":{
        "Id":62717390,
        "Name":"sdfsdfsdf",
        "Avatar":""
    },
    "Type":"IMAGE",
    "Created":"\/Date(1475669802713+0000)\/",
    "LastModified":"\/Date(1475669802713+0000)\/",
    "IsComment":0,
    "IsStuck":0,
    "IsDeleted":0,
    "IsApproved":0,
    "Media":[
        {
            "Type":"IMAGE",
            "Url":"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61.jpg"
        }
    ],
    "Source":"",
    "EventId":2349523,
    "PostMeta":{
        "Images":"[{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61_500.jpg\",\"width\":500,\"height\":375},{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61_400.jpg\",\"width\":400,\"height\":300},{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61.jpg\",\"width\":600,\"height\":450},{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61_800.jpg\",\"width\":800,\"height\":600},{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61_300.jpg\",\"width\":300,\"height\":225},{\"filename\":\"https://images.scribblelive.com/2016/10/5/97555340-73f3-4c0d-9cdc-b976df18ef61_1000.jpg\",\"width\":1000,\"height\":750}]",
        "CreationDate":1475669802
    }
}`

But i don't see anything up in the scribblelive event writer. 
When i submit the form without a file the comment is correctly displayed in the scribblelive admin and the json response is like that : 

`{
    "Message":"In moderation",
    "Code":200
}`

Can you help me ?

Thank you very much.

**Comment by sagarasouske** [comment]
Hi Iasdou,

I assume you are using Content Studio on the backend, it is a known issue that images send with this version of comment sample don't show up in the Moderation Hub. We are working on an improved version of the comment sample unfortunately it is not ready for release yet.

Please send any further inquiries to support@scribblelive.com via email or if you are logged in into the scribblelive backend please fill out the form that you get when clicking the (?) -> support link.

If you want to be updated for this request please also send the current request via one of the aforementioned methods to support.

Best Regards.
